language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: webdevandsausages
  api_key:
    secure: NdBAr47LF8zZvrQWFegLXO71bZIjbWFpcbv+/fvrSGvOvIhWwPOX+eNcZP1yx/zoNI8hOqs3SHaoGnLxH5WV9QyRstUoyTbFYcueBsPRUdDz4/HL2yyZ7NSOHgZrlzTq9go0r2EJJnFHRAGzYkvzMf+ouuaooJX8sixc36y9/rudAYwpsc1Nf04GCzdhYiqTLIAyydE2xtCAIxfVxnk+zqbSnQKGaz/lzIGutwpz5gX3VXglOZL56BUREMTlgxrAvkkJhhLujU2XN7euU26upPXLiL+4I2EsTnOpjAExB7E3VI8T+WJe4ldMQIRcvaZLtHlXnG2fLOvr2zFS6eHR1IgxMOXAfXAZ9eh4OQ4lYQpKdpuC5MPVOOsVo7572y1/C8TeV0CUnZG73UJ/NUAucgfR3sKOQ6jMPe0HBiLIulvx0ZVyG6VKHPHEYUOiGOe/ei+6cYCh9swCE7RCwjNk5o+HA6pexuVduVRfoSl7e/bDx5CylWRrPbePWVAj/D2EHO3oWeqg6755f45IvztP8O/WE70i1xdZ3v9CY3+ed8GZHJmUeGdHmijyZ3QIwUv7pRvt3mhCwSsCuSrBcDeHOdGIu76GExgaRZ52IBYvprcMm1fcyctj4HxFZiLI6wSeRcO1yc9JmB3wG73E3y4E4bQsG7r9hSXFibuprmUCVQY=
